#ifndef QTHEADERS_H
#define QTHEADERS_H
#include <QWidget>
#include <QObject>
#include <QDebug>
#include <QString>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QBoxLayout>
#include <QStackedLayout>
#include <QLineEdit>
#include <QTextEdit>
#include <QPushButton>
#include <QToolButton>
#include <QLabel>
#include <QMouseEvent>
#include <QEvent>
#include <QVector>
#include <QListView>
#include <QTreeView>
#include <QTableView>
#include <QScrollArea>
#include <QScrollBar>
#include <QContextMenuEvent>
#include <QMenu>
#include <QPoint>
#include <QModelIndex>
#include <QTableWidget>
#include <QListWidget>
#include <QStackedWidget>
#include <QStyledItemDelegate>
#include <QSpaceritem>
#include <QMessageBox>
#include <QSettings>
#include <QCommonStyle>

#endif // QTHEADERS_H
